### PR TITLE
[WIP] counsel support

### PR DESCRIPTION
**Pull request by FelipeLema**
Support [counsel](https://github.com/abo-abo/swiper). Solves #175.

- [x] Unit tests (so we don't break anything)
- [ ] Add documentation (I don't fully understand code that must be modified)
- [ ] Break functionality into smaller functions (needed refactor). Right now, several functions are tied to `compile-mode`. `grep` for `compilation-start` for a sample.
- [ ] Single-parameter option to use either `compilation-mode` API or `counsel`'s. Probably a `defcustom`

### CODE REVIEW

**Comment by Ergus** [comment]
Hi Felipe:
Whats the actual status of your counsel support? Can be used already? I am specially interested in the tramp support.
I see that your fork has been modified recently (at least more recent than melpa's package.) Why don't you add your version to melpa. So more users can use it, report issues and contribute? 
Very thanks for your work
Ergus

**Comment by FelipeLema** [comment]
Hey, Ergus

Thanks for the compliment, but I didn't get to add much to this package. Reasons for why I didn't continue with this are [here](https://github.com/leoliu/ggtags/issues/175#issuecomment-428986369).

As mentioned, I'd recommend you check [my fork](https://github.com/FelipeLema/emacs-counsel-gtags) of [`emacs-counsel-tags`](https://github.com/syohex/emacs-counsel-gtags).

**Comment by FelipeLema** [comment]
Also, I'm working on a revamp of "using global" by doing an Emacs Lisp API and plugging this API to Emacs using `project.el` and `xref.el`

https://code.launchpad.net/~morenonatural/global-tags.el/+git/global-tags.el

**Comment by Ergus** [comment]
Hi Felipe:
Sorry to add comments here, but for some reason there is not an issues section in your fork, so this was the only way I found to contact you. What about adding the changes in your fork to melpa? It is a very straightforward procedure. 
So users can get automatically your changes to emacs-counsel-tags which adoption will be very welcome for the community and probably some others will collaborate!!! We are discussing In the emacs mailing list about adding some support to gtags within emacs and your experience could be very welcome too.

**Comment by FelipeLema** [comment]
Hey, Ergus... I've [opened the PR for using my fork for `counsel-gtags` package ](https://github.com/melpa/melpa/pull/6093) and you can now add issues on my fork.

**Pull request closed without merging**
