### PR TITLE
Add Xref support

### LINKED ISSUE #160: add xref back end
Newer version of Emacs bind `M-.` and friends to `xref-*` functions (see `xref.el`) rather than to etags functions directly.  `xref` allows multiple back ends, so I think it would be good for ggtags to be another xref back end; without rebinding the various keys.

### PR DESCRIPTION
**Pull request by dzop**
Closes #160

### CODE REVIEW

**Comment by leoliu** [comment]
Thanks. Could you restrict the pull request to just adding xref support?

**Comment by dzop** [comment]
So you want me to split this into two pull requests, the changes to `ggtags-global-output` and then the `xref` support?

**Comment by leoliu** [comment]
@dzop I want this pull request to be only about XREF support. For example, the first commit I have no idea where it comes from.

**Comment by dzop** [comment]
Oh I see. Yes the other commits are mainly bug fixes and slight improvements to `ggtags-global-output`. 

I will close this pull request and make another one.

**Pull request closed without merging**
