### PR TITLE
GNU Global 6.5 has renamed plugin-factory/README

### PR DESCRIPTION
**Pull request by egarrulo**

### CODE REVIEW

**Comment by leoliu** [comment]
Thanks for the PR but you might have a typo there. Do you mean `PLUGIN_INFO`?

**Comment by egarrulo** [comment]
No typo.  There is no `PLUGIN_INFO` in the directory:

    $ ls plugin-factory/
    exuberant-ctags.c  Makefile.in   PLUGIN_HOWTO.pygments  pygments_parser.py     user-custom.c
    Makefile.am        PLUGIN_HOWTO  pygments-parser.c      pygments_parser.py.in

And `PLUGIN_HOWTO` contains the lines:

        $ cat plugin-factory/PLUGIN_HOWTO | grep -C 3 with-exuberant-ctags

        It assumed that ctags command is installed in '/usr/local/bin'.

        $ ./configure --with-exuberant-ctags=/usr/local/bin/ctags
        $ make
        $ sudo make install

**Comment by leoliu** [comment]
hi @egarrulo,

I meant `PLUGIN_HOWTO`. Could you correct your PR too? I'll merge asap. Thanks.

Leo

**Comment by egarrulo** [comment]
Oh my!  I can't believe that I missed that.  Sorry.  And fixed.  Thanks for your patience.

**Comment by leoliu** [comment]
The fix doesn't come through this PR. So I did a manual merge. Thanks again.

**Pull request closed without merging**
