### PR TITLE
Use call-process to run global synchronously with xref backend

### PR DESCRIPTION
**Pull request by gmlarumbe**
Hi,

First of all, thanks for the great package.

Recently, on some specific machines with Emacs 29, I have been experiencing some issues that I have not been able to reproduce deterministically. From time to time, Emacs hangs while navigating definitions/references with `xref` and `ggtags` backend. 

After some debugging, I found out that this has to do with the use of `ggtags-global-output` with the `'sync` option in the  `ggtags--xref-find-tags` function.
The synchronous wait for tags collection is performed through some polling on the `:callback-done` property of the sentinel:
```elisp
; ggtags-global-output let* section
(sentinel (lambda (proc _msg)
                     (when (memq (process-status proc) '(exit signal))
                       (with-current-buffer (process-buffer proc)
                         (set-process-buffer proc nil)
                         (unwind-protect
                             (funcall callback (process-exit-status proc))
                           (process-put proc :callback-done t))))))
```
```elisp
; ggtags-global-output body end
    (if sync (while (not (process-get proc :callback-done))
               (accept-process-output proc 1))
      proc)))
```
After adding some traces inside the `while` loop, it showed that from time to time, function would never exit because the property would not be set.

I suggest some changes using `call-process` to run the `global` command synchronously with `xref`. I have tested them locally and everything seems to work fine.

Thanks!

### CODE REVIEW

**Comment by leoliu** [comment]
@gmlarumbe thanks for the PR and sorry for the delay.  Long ago I discovered `call-process` is much faster for small output but there is an inflection point. I wonder if you are able to track down why `:callback-done` is not set? We may need to augment the list `(exit signal)`.

**Comment by gmlarumbe** [comment]
Hi @leoliu ,

I have tried adding more elements to the list of process status:
```emacs-lisp
(sentinel (lambda (proc _msg)                                                                                
            (when (memq (process-status proc) '(exit signal run stop open listen closed connect failed))
              (with-current-buffer (process-buffer proc)                                                
                (set-process-buffer proc nil)                                                           
                (unwind-protect                                                                         
                    (funcall callback (process-exit-status proc))                                       
                  (process-put proc :callback-done t)))))))                                             
```
However, after some searches it gets stuck again.

I believe one possibility could be that the sentinel is not being executed and therefore it never changes the `:callback-done` property. Since function local bindings are done sequentially with the `let*` form, my guess is that `proc` has already finished before the sentinel is set, preventing the sentinel from detecting any process status changes.

I did not have that much time for debugging, but hope that could be useful.

**Comment by leoliu** [comment]
@gmlarumbe thanks for taking the time to look into this.

Yes indeed there is a small window that could happen. Looking at `ggtags-global-output` there is no reason to wait forever when the proc is no longer alive. I wonder if the following patch may help?

```
diff --git a/ggtags.el b/ggtags.el
index ba14d883..7d8bf302 100644
--- a/ggtags.el
+++ b/ggtags.el
@@ -1993,7 +1993,6 @@ (defun ggtags-global-output (buffer cmds callback &optional cutoff sync)
                                            (with-current-buffer buffer
                                              (line-number-at-pos (point-max)))
                                          0))))
-         (proc (apply #'start-file-process program buffer program args))
          (filter (lambda (proc string)
                    (and (buffer-live-p (process-buffer proc))
                         (with-current-buffer (process-buffer proc)
@@ -2009,17 +2008,15 @@ (defun ggtags-global-output (buffer cmds callback &optional cutoff sync)
                      (when (memq (process-status proc) '(exit signal))
                        (with-current-buffer (process-buffer proc)
                          (set-process-buffer proc nil)
-                         (unwind-protect
-                             (funcall callback (process-exit-status proc))
-                           (process-put proc :callback-done t)))))))
+                         (funcall callback (process-exit-status proc))))))
+         (proc (apply #'start-file-process program buffer program args)))
+    (set-process-sentinel proc sentinel)
     (set-process-query-on-exit-flag proc nil)
     (and cutoff (set-process-filter proc filter))
-    (set-process-sentinel proc sentinel)
-    (process-put proc :callback-done nil)
     (process-put proc :nlines 0)
-    (if sync (while (not (process-get proc :callback-done))
-               (accept-process-output proc 1))
-      proc)))
+    (while (and sync (process-live-p proc))
+      (accept-process-output proc 1))
+    proc))
 
 (cl-defun ggtags-fontify-code (code &optional (mode major-mode))
   (cl-check-type mode function)
```

**Comment by gmlarumbe** [comment]
Hi @leoliu ,

Thanks for the patch! I applied it at [gmlarumbe/xref-sync-patch](https://github.com/gmlarumbe/ggtags/tree/xref-sync-patch) and now it does not freeze but it still gives an `xref--not-found-error` from time to time. I have repeatedly tried to search for definitions of a tag named `addr` to see after how many attempts it fails:
```
[ggtags] Defs of: addr [79 times]
xref--not-found-error: No definitions found for: addr
[ggtags] Defs of: addr [267 times]
xref--not-found-error: No definitions found for: addr
[ggtags] Defs of: addr [120 times]
xref--not-found-error: No definitions found for: addr
```
Using `call-process` it does not fail after more than 2k attempts:
```
[ggtags] Defs of: addr [2030 times]
```

**Comment by leoliu** [comment]
@gmlarumbe thanks for the stats. I am in favour of your solution.

```
(with-current-buffer buffer
      (save-excursion
        (goto-char (point-min))
        (forward-line (1+ cutoff))
        (unless (eobp)
          (kill-region (point) (point-max))))
      (funcall callback status))
```

Could you remove the `save-excursion` from the above? I think if Emacs has already done the hard work of getting the output we should keep it. `cutoff` in `ggtags-global-output` is also never precise, for example if you set it to 4, you might get 100 but normally not 10000.

**Comment by gmlarumbe** [comment]
@leoliu thanks for the suggestion, makes sense to keep the results.

I have force-pushed the new changes in 98f978a

Thanks!

**Comment by leoliu** [comment]
@gmlarumbe merged. Thanks for the patience and contribution!

**Pull request merged**
